### PR TITLE
Request to add project Crypto Spirits

### PR DESCRIPTION
**Pull request by DigitalCloudz**
logo-crypto-spirits

[project.md](https://github.com/Zilliqa/zil-ecosystem/files/8122107/project.md)

### CODE REVIEW

**Review by AshIgnYeo — CHANGES_REQUESTED** [review]
@DigitalCloudz your PR is missing its properly formatted project.md file. Please review the README for instructions on how to format the PR for acceptance. Thanks!

**Comment by DigitalCloudz** [comment]
@AshIgnYeo I have made some corrections which should fit the format project.md file. Hopefull all is in order. Thank you!

**Review by AshIgnYeo — CHANGES_REQUESTED** [review]
Hi @DigitalCloudz you can see from the screenshots below that the project is not formatted properly. 

### from your fork
Screenshot 2022-02-24 at 11 22 56 AM

### from your PR
Screenshot 2022-02-24 at 11 22 37 AM

Please ensure that the logo and project.md file are in a folder called crypto-spirits
```
projects
   |- crypto-spirits
       |- project.md
       |- (logo file)
```

**Comment by Elliott-Green** [comment]
@DigitalCloudz Closing this due to inactivity, feel free to submit another PR with the correct data.

**Pull request closed without merging**
